### ISSUE TITLE
Jedis 2.7.2 JedisConnectionFactory error with spring-data-redis.1.5.1.RELEASE

### ISSUE THREAD

**Issue by cjm0000000** [xetorthio/jedis#1043] opened 2015-07-02 13:48 UTC
Below is the test code:
    
    JedisConnectionFactory redisConnectionFactory = new JedisConnectionFactory();
        redisConnectionFactory.setHostName("10.45.8.124");
        redisConnectionFactory.setPort(6379);
        redisConnectionFactory.setPoolConfig(new JedisPoolConfig());
        redisConnectionFactory.setUsePool(true);
        redisConnectionFactory.setPassword("pass");
        redisConnectionFactory.afterPropertiesSet();

        RedisTemplate<String, String> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.setKeySerializer(new StringRedisSerializer());

        redisTemplate.afterPropertiesSet();

        redisTemplate.delete("a");

And the stacktrace is:

    Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:252)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:58)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:128)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:91)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:78)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
	at org.springframework.data.redis.core.RedisTemplate.delete(RedisTemplate.java:600)
	at com.best.neptune.common.biz.test.Main.main(Main.java:29)
    Caused by: java.lang.NullPointerException
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:443)
	at org.springframework.data.redis.connection.jedis.JedisConnection.<clinit>  (JedisConnection.java:108)

When I change the jedis to version `2.6.1`, It works!
Can anybody tell me what happened?

Thanks

**Comment by valleylord** [comment] 2015-07-03 08:45
I face the same error with yours. Maybe it is spring-data-redis's bug. The exception throws when a spring-data-redis Connection class(or maybe someother class) initialize. During initialization, the class first goes into its static code part. In this part, it wants to get jedis sendcommand method by reflection, but the reflection does not return any thing since it pass the wrong param type.

So, i just simply use jedis 2.7.2. It's also good. ^_^

**Comment by valleylord** [comment] 2015-07-03 09:05
The exception was thrown from JedisConnection class. If everything's right, JedisConnectionFactory class will create JedisConnection instance. But the exception happens here, 

```
	static {
		CLIENT_FIELD = ReflectionUtils.findField(BinaryJedis.class, "client", Client.class);
		ReflectionUtils.makeAccessible(CLIENT_FIELD);
		SEND_COMMAND = ReflectionUtils.findMethod(Connection.class, "sendCommand", new Class[] { Command.class,
				byte[][].class });
		ReflectionUtils.makeAccessible(SEND_COMMAND);
		GET_RESPONSE = ReflectionUtils.findMethod(Queable.class, "getResponse", Builder.class);
		ReflectionUtils.makeAccessible(GET_RESPONSE);
	}

```

in line `SEND_COMMAND = ...` it wants to get sendCommand method by reflection, but it passes the wrong param. So `SEND_COMMAND` is null, and exception throws at the next line.

That's all the story. It confuses me nearly 24 hours. haha

**Comment by marcosnils** [comment] 2015-07-03 11:24
@cjm0000000 @valleylord seems like a spring-redis thing. I'm wondering however how it breaks from 2.6 to 2.7 as we supposedly didn't introduce any breaking backwards compatibility change. 

Can you please open an issue into the spring-data-redis list and copy it here?

Thx.

**Comment by HeartSaVioR** [comment] 2015-07-04 03:57
@cjm0000000 @valleylord @marcosnils 
https://github.com/spring-projects/spring-data-redis/pull/139
It is already addressed but Spring-data-redis doesn't take the PR.

We're not breaking backwards compatibility but reflection seems to find method by exact signature match. (Am I right?)

**Comment by valleylord** [comment] 2015-07-06 00:58
I thought Jedis 2.7 may change the param of `sendCommand` from `Command.class` to some others. So Spring-redis doesn't work on Jedis 2.7. I am not sure it is right.

BTW, if you don't user redis 3.0's fetures, maybe Jedis 2.6 is also a good choice.

**Comment by HeartSaVioR** [comment] 2015-07-06 04:20
@valleylord @cjm0000000 @marcosnils 
Yes, right. We changed first argument of sendCommand() from ```Command```, which is a class to ```ProtocolCommand```, which is an interface. 
I don't exactly know it can break "binary" compatibility, but at lease it breaks reflection as Spring-data-redis shows.

**Comment by marcosnils** [comment] 2015-07-07 00:45
Just came across this tool which analyses binary compatibility between two jar files: https://github.com/lvc/japi-compliance-checker/

I've run it against 2.6.3 and 2.7.2 and effectively we've broken Binary Compatibility in the `sendCommand` function.
https://dl-web.dropbox.com/get/Public/compat_reports/jedis/2.6.3_to_2.7.2/compat_report.html?_subject_uid=29887388&w=AAA-Oaoh_lDnhgP4OOlG_f1RrS9vJq3ZfDMzIn4oeTykPQ

@HeartSaVioR @xetorthio we made this change to re-use jedis core into jedisque. Seems like we missed the binary compatibility for this change. I'd recommend reverting this change and release 2.7.3 to fix this.

What do you think?

**Comment by HeartSaVioR** [comment] 2015-07-07 01:54
@marcosnils @xetorthio 
Seems like we're in stuck.
I agree to revert it and keep binary compatibility again, but also we should make an effort to release 3.0.0 somewhat faster. All of planned features we can apply to 2.8.0 could be applied to 3.0.0, and something is already done.

**Comment by HeartSaVioR** [comment] 2015-07-07 01:57
@marcosnils @xetorthio How about making beta release of 3.0.0 and let Jedisque uses it?

**Comment by marcosnils** [comment] 2015-07-20 12:44
Hi, Jedis 2.7.3 has been released which fixes this issue, @cjm0000000 @valleylord can you please check if this is fixed with the new version?.

Thx, and apologize for the inconvencientes!.

**Comment by marcosnils** [comment] 2015-07-21 00:29
this is confirmed to be fixed here https://github.com/spring-projects/spring-data-redis/pull/139.

**Closed by marcosnils** 2015-07-21 00:29 UTC

**Comment by cjm0000000** [comment] 2015-07-29 06:26
@malomalo  I upgrade jedis client to `2.7.3`, it works! 
Thanks all!
