### ISSUE TITLE
Pipelined operations Timeout on second use of pipelined on the same connection

### ISSUE THREAD

**Issue by JAlexoid** [xetorthio/jedis#1259] opened 2016-04-18 23:55 UTC
### Expected behavior

Expecting unlimited number of calls to pipelined without socket excetpions

### Actual behavior

Second time a pipeline is created on the same connection, the second result of a incrBy causes a timeout exception

java.lang.RuntimeException: java.lang.RuntimeException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at pipeline.lambda.LogFileHandler.handleHeartbeatNotification(LogFileHandler.java:126)
	at pipeline.lambda.LogFileHandler.handleRequest(LogFileHandler.java:69)
	at pipeline.lambda.SNSLogFileHandler.handleNotification(SNSLogFileHandler.java:147)
	at pipeline.lambda.SNSLogFileHandler.handleRequest(SNSLogFileHandler.java:130)
	at pipeline.FakeLambdaRunner.main(FakeLambdaRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at pipeline.processors.LogFileProcessor.handleNotification(LogFileProcessor.java:162)
	at pipeline.lambda.LogFileHandler.handleHeartbeatNotification(LogFileHandler.java:123)
	... 10 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getAll(Connection.java:267)
	at redis.clients.jedis.Connection.getAll(Connection.java:259)
	at redis.clients.jedis.Pipeline.sync(Pipeline.java:99)
	at pipeline.shared.cache.RedisCountingCache.incrementPartitionGrainBy(RedisCountingCache.java:84)
	at pipeline.processors.CounterCapture.captureCounters(CounterCapture.java:117)
	at pipeline.processors.LogFileProcessor.handleNotification(LogFileProcessor.java:141)
	... 11 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
	... 21 more
### Steps to reproduce:

Create one pipeline 
Stack up a bunch of incrBy(more than 10)
Sync the pipeline
Get the results back from Result<Long> objects

Without closing the connection or recreating the Jedis object

Create a new pipeline
Stack up a bunch of incrBy(more than 10)
Sync the pipeline (exception occurs)

#### Java version: "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by JAlexoid** [comment] 2016-04-18 23:59
Does another exception : 
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getAll(Connection.java:267)
	at redis.clients.jedis.Connection.getAll(Connection.java:259)
	at redis.clients.jedis.Pipeline.sync(Pipeline.java:99)

**Comment by HeartSaVioR** [comment] 2016-04-20 00:58
When JedisConnection is raised, it indicates that Jedis instance is invalid now, so you should discard that instance and recreate or re-borrow instance. There's no except for Pipeline.

Thanks for creating an issue, but not an issue. Closing.

**Closed by HeartSaVioR** 2016-04-20 00:58 UTC

**Comment by JAlexoid** [comment] 2016-04-20 01:25
So... That means that using a pipeline once invalidates the whole instance? Nice to know.
FYI: Switching to non-pipelined operations works 100% of the time.

**Comment by HeartSaVioR** [comment] 2016-04-20 01:34
No, when only your pipeline throws JedisConnectionException. :)

**Comment by JAlexoid** [comment] 2016-04-20 01:36
That's the bug - it always throws JedisConnectionException when you create a second Pipeline after syncing the first one.

**Comment by HeartSaVioR** [comment] 2016-04-20 01:38
Didn't you receive the exception when you sync the first Pipeline? If not please reopen this issue so I can take a look.

**Comment by srirama-rayaprolu** [comment] 2016-07-18 12:45
Am checking the connection status (open/closed) and then firing the pipe line command then also throwing the Timeout exception. 
How can I identify the connection is valid for "Pipelined operations"? any dummy operations for pipeline?

**Comment by xetorthio** [comment] 2016-07-19 01:55
Not sure I understand your question. Mind giving an example of what you are trying to do?
@JAlexoid Can you please confirm if you always get a `JedisConnectionException` even if the first pipeline worked fine and no exception was thrown?

**Comment by srirama-rayaprolu** [comment] 2016-07-19 06:47
In my app, creating pipe line from JEDIS Connection, after that executing the commands. This is working fine.

However my app need to support re-connectivity. Hence, restarting the REDIS server without restarting the application. In this scenario, before opening the pipe line, am checking the connection status, if it is not connected, am connecting again. After that, executed one sample set (key) command. Once this successful, am opening the pipe line and sending the commands to server. I am getting time out for pipe line command response. 

When checked in the TCP dump and in the REDIS monitor, the commands executed on pipe line are present. However my app received the Time-Out Exception.

**Comment by xetorthio** [comment] 2016-07-19 12:29
So if I understand correctly you are opening a connection to redis, restart
redis and then try to use that connection? You first run a set command to
make sure connection is healthy and then open a pipeline and send commands?
Did I get it right?

**Comment by srirama-rayaprolu** [comment] 2016-07-20 06:12
Yes correct. The following code excerpt I used, for fetching the pipe line from Jedis. My class is extending the Jedis class. 
```java
public Pipeline pipelined() {
    boolean ioErrorOccured = true;
    Pipeline pipeline = null;
    do {
        try {
            if (isConnected() == false)
            {
                connect();
            }
            set("testing", "connection");
            pipeline=super.pipelined();
            ioErrorOccured = false;
        } catch (final redis.clients.jedis.exceptions.JedisConnectionException e) {
            connect();
        }
    } while (ioErrorOccured == true);
    return pipeline;
}
public void connect() {
    try {
        if (super.isAlive()) {
            return;
        }
        try {
            super.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
        super.connect();
        super.ping();
        return;
    } catch (Exception e) {
        return;
    }
}

```

**Comment by xetorthio** [comment] 2016-07-20 15:45
Ok. I'll try to reproduce what you're reporting and check if there is an
error and where it is. I'll report back on this issue.

**Comment by srirama-rayaprolu** [comment] 2016-07-21 11:58
@xetorthio: Thanks for the reply.

On further debugging, it was identified, in my re-connectivity logic, need to reset pipelinedCommands to zero on Jedis Connection object . Otherwise this problem is coming.

It could be, in my app, some places the pipelinedCommands counter was increased and waiting for response. In between the connection got lost and the counter was not reset to zero as part of reconnect logic.

If connection was reset, in the middle of waiting for response, REDIS wont give the old responses, but the counter is still >0 and hence the problem of timeout for pipe line calls after reconnect.

In the disconnect of JEDIS object, the pipelinedCommands counter should be reset to zero ???

**Comment by xetorthio** [comment] 2016-07-21 16:52
Yes. What you described could definitely be the problem. When you
disconnect the counter should be set to 0.

**Comment by srirama-rayaprolu** [comment] 2016-08-11 15:00
@xetorthio: Now I am facing different issue different issue while using evalsha. (I know it is not related to pipelined). My code is as below,

```java
@Override
	public Object evalsha(String sha1, int keyCount, String... params) {
		boolean ioErrorOccured = true;
		Object obj = null;
		do {
			try {
				obj = super.evalsha(sha1, keyCount, params);
				ioErrorOccured = false;
			} catch (final redis.clients.jedis.exceptions.JedisConnectionException e) {
				// TODO reconnect to the server
				// super.connect();
				connect();
			}
		} while (ioErrorOccured == true);
		return obj;
	}
```

I am getting the following error, what could be the mistake I am making, pls. guide me.

```
redis.clients.jedis.exceptions.JedisDataException: NOSCRIPT No matching script. Please use EVAL.
        at redis.clients.jedis.Protocol.processError(Protocol.java:115)
        at redis.clients.jedis.Protocol.process(Protocol.java:141)
        at redis.clients.jedis.Protocol.read(Protocol.java:196)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283)
        at redis.clients.jedis.Connection.getOne(Connection.java:265)   
        at redis.clients.jedis.Connection.getOne(Connection.java:265)
        at redis.clients.jedis.Jedis.getEvalResult(Jedis.java:2907)
        at redis.clients.jedis.Jedis.evalsha(Jedis.java:2934)
        at redis.clients.jedis.custom.Jedis.evalsha(Jedis.java:57)      
````

**Comment by xetorthio** [comment] 2016-08-11 17:23
This error is redis telling you that there is no script in redis with the
sha you're passing. You either need to use EVAL and send the script every
time you want to execute it, or do a SCRIPT LOAD previously to get the SHA
and then be able to run it, with EVALSHA, and avoid sending the script
every time.

**Comment by shizhengchao** [comment] 2019-01-25 02:16
You can check the settings of your redis server timeout:
using this command: config get timeout.，default is 0, means never timeout
If your operation interval is greater than this value,you will get the exception:

`redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
at redis.clients.jedis.Protocol.process(Protocol.java:141)
at redis.clients.jedis.Protocol.read(Protocol.java:205)
at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
at redis.clients.jedis.Connection.getAll(Connection.java:267)
at redis.clients.jedis.Connection.getAll(Connection.java:259)
at redis.clients.jedis.Pipeline.sync(Pipeline.java:99)`

so you will catch the exception and retry get a connection. like jedisCluster do:
`catch (JedisConnectionException jce) {
      // release current connection before recursion
      releaseConnection(connection);
      connection = null;
      if (attempts <= 1) {
        //We need this because if node is not reachable anymore - we need to finally initiate slots renewing,
        //or we can stuck with cluster state without one node in opposite case.
        //But now if maxAttempts = 1 or 2 we will do it too often. For each time-outed request.
        //TODO make tracking of successful/unsuccessful operations for node - do renewing only
        //if there were no successful responses from this node last few seconds
        this.connectionHandler.renewSlotCache();

        //no more redirections left, throw original exception, not JedisClusterMaxRedirectionsException, because it's not MOVED situation
        throw jce;
      }
      **return runWithRetries(key, attempts - 1, tryRandomNode, asking)**;`
