### ISSUE TITLE
Improve clusterSlots response

### ISSUE THREAD

**Issue by xetorthio** [xetorthio/jedis#1346] opened 2016-07-08 14:00 UTC
### Expected behavior

Maybe `List<SlotAssignment>` where `SlotAssignment` is:
```java
class SlotAssignment {
  int start
  int end
  Node master
  List<Node> replicas
}
```

And `Node` is:
```java
class Node {
  HostAndPort net
  String key
}
```
### Actual behavior

```java
List<Object>
```

**Comment by marcosnils** [comment] 2016-07-09 11:45
Dupe of https://github.com/xetorthio/jedis/issues/988. Let's continue on that thread.

**Closed by marcosnils** 2016-07-09 11:45 UTC

**Comment by xetorthio** [comment] 2016-07-09 12:07
Not sure if it is the same. The other issue is about nodes and this one
about slots.

**Comment by marcosnils** [comment] 2016-07-09 12:22
The conversion in the thread also suggests adding slots info. I've just updated the issue title so it's more representative
