### ISSUE TITLE
[Feature request]make a super Interface for BinaryJedisClusterCommands and BinaryJedisCommands

### ISSUE THREAD

**Issue by jiming** [xetorthio/jedis#1692] opened 2017-12-07 12:15 UTC
### Expected behavior

`BinaryJedisClusterCommands` and `BinaryJedisCommands` can have a same super Interface, since a lot of method of them are same. Sometime, I do not need aware of BinaryJedisClusterCommands or BinaryJedisCommands, as I just need set/get/mset ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Jedis version:
2.9.0

**Comment by sazzad16** [comment] 2018-01-22 01:01
Duplicate of #1545

**Closed by sazzad16** 2018-01-22 01:01 UTC
