### ISSUE TITLE
"Error : java.lang.Long cannot be cast to [B" when trying evalsha command with Pipeline

### ISSUE THREAD

**Issue by mayankdang** [xetorthio/jedis#916] opened 2015-03-09 14:27 UTC
I know there are several "similar" issues, but none of the errors reported earlier (#663, for example) is the same as the one I am getting.
Versions: Jedis 2.6.2
Maven dependency :  

```
<dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.6.2</version>
</dependency> 
```

Redis Versions: Tested with both current unstable branch (3.1.999) and official release 2.8.13.

Code : 

```
public List<Object> wowDude(int db, int choice) throws Exception {
        Jedis jedis = null;
        jedis = getJedis(db, choice, jedis);
        Pipeline pipeline = jedis.pipelined();
        pipeline.del("ping");
        pipeline.evalsha("4685a09f15d2b2532b034d340b80004349e4462b", 1, "lol", "omg245324", "___");
        pipeline.del("omg2");
        List<Object> list = pipeline.syncAndReturnAll();
        returnJedis(choice, jedis);
        return list;
}
```

where getJedis and returnJedis are simple methods that call `getResourse()` and `returnResource()` from / to the JedisPool, a static variable.

The lua script code is 

``` lua
-- first ensure number of keys to be 1 and number of arguments to be 2
-- first key - hash's name
-- first argument - key value
-- second argument - value to append
if ((table.getn(ARGV) == 2) and (table.getn(KEYS) == 1)) then
    if redis.call("HEXISTS", KEYS[1], ARGV[1]) == 1 then
        local val = redis.call("HGET", KEYS[1], ARGV[1])
        return redis.call("HSET", KEYS[1], ARGV[1], val..","..ARGV[2])
    else
        return redis.call("HSET", KEYS[1], ARGV[1], ARGV[2])
    end
end
```

and the sha1being passed through jedis is the same as the `script load` redis command and the `sha1sum` linux command of the above lua script.

The stack trace is:

```
ERROR com.testSuite.servlets.TestServlet3 [] -java.lang.Long cannot be cast to [B
" java.lang.ClassCastException: java.lang.Long cannot be cast to [B
    at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:56) ~[jedis-2.6.2.jar:?]
    at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:54) ~[jedis-2.6.2.jar:?]
    at redis.clients.jedis.Response.build(Response.java:50) ~[jedis-2.6.2.jar:?]
    at redis.clients.jedis.Response.get(Response.java:35) ~[jedis-2.6.2.jar:?]
    at redis.clients.jedis.Pipeline.syncAndReturnAll(Pipeline.java:105) ~[jedis-2.6.2.jar:?]
    at com.testSuite.utils.JedisClient.wowDude(JedisClient.java:317) ~[JedisClient.class:?]
    at com.testSuite.servlets.TestServlet3.doGet(TestServlet3.java:51) [TestServlet3.class:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621) [servlet-api.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.47]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat7-websocket.jar:7.0.47]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.47]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.47]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.47]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.47]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.47]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.47]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.47]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote.jar:7.0.47]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-coyote.jar:7.0.47]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.47]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_25]
    at java.lang.Thread.run(Thread.java:724) [?:1.7.0_25]

```

PS. The call succeeds (the value gets appended to the value of the key in the hash specified, but I get the error, while the list is being returned to me by `syncAndReturnAll()` function.
PPS. The error is not received if I call `sync()` instead of `syncAndReturnAll()` of `Pipeline.java`.

Also,
The error doesn't come if the lua script is modified to:

``` lua
if ((table.getn(ARGV) == 2) and (table.getn(KEYS) == 1)) then
    if redis.call("HEXISTS", KEYS[1], ARGV[1]) == 1 then
        local val = redis.call("HGET", KEYS[1], ARGV[1])
        redis.call("HSET", KEYS[1], ARGV[1], val..","..ARGV[2])
    else
        redis.call("HSET", KEYS[1], ARGV[1], ARGV[2])
    end
end
return "str"  -- any constant string
```

**Comment by mayankdang** [comment] 2015-03-09 14:35
Also, this has nothing to do with multi threading, as I have read in some previous issues, since this is a single get servlet call, that gets a resource from the pool, makes an evalsha call via pipeline, and returns the resource from the pool.
Moreover, the call succeeds (the value gets appended to the value of the key in the hash specified), but I get this error, which doesn't come up during the call to ``` sync() ``` .

**Comment by HeartSaVioR** [comment] 2015-03-09 22:38
It's known bug and already fixed by #607.
But it requires change of method signature, so with semver we're planning to apply fix to 3.0.0.

@xetorthio @marcosnils @nykolaslima 
Maybe we should release 3.0.0 earlier cause it fixes some method signature issues which shows strange behavior.

**Comment by HeartSaVioR** [comment] 2015-03-09 22:39
@mayankdang You're encouraged to use eval without Pipeline. Sorry for inconvenience. ;(

**Comment by nykolaslima** [comment] 2015-03-09 23:53
huum...I'm not sure about it. Because if we release the 3.0.0, after it we will change the entire structure and will need to name it 4.0.

Since it's a bug fix, shouldn't be better to apply it to 2.7 even knowing it will change the method signature?
I believe it's better than let a known bug opened.

**Comment by HeartSaVioR** [comment] 2015-03-10 00:32
@nykolaslima 
We will try our best to apply any breaking changes before releasing 3.0.0. So don't worry about 4.0 yet.

Btw, keeping compatibility between minor releases is very important. 
I don't like such libraries which often break compatibility so I need to rewrite code when I update the library because of bugfix.

But it's important to let users know we're not recommended to use these methods now.
So how about this approach?
We can deprecate methods at 2.x with enough description, and restore methods at 3.0.0.

@xetorthio @marcosnils

**Comment by nykolaslima** [comment] 2015-03-10 01:40
But will we release 3.0.0 before other changes?

**Comment by HeartSaVioR** [comment] 2015-03-10 05:04
@nykolaslima 
We're having issues or PRs with 3.0.0 milestone. 
We will check milestone again when we feel it's time to release.

**Comment by sradeep-d** [comment] 2017-01-03 11:05
Hi @HeartSaVioR ,
I am presently using version 2.9.0 with the issue "java.lang.Long cannot be cast to [B".
Would like to the plan of releasing the fix.

**Comment by inponomarev** [comment] 2017-01-08 18:23
Hello, all! I am using 2.8.1 and recently started to get ClassCastExceptions both ways:

java.lang.ClassCastException: [B cannot be cast to java.lang.Long
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:222)
	at redis.clients.jedis.Jedis.ttl(Jedis.java:308)

java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:216)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:205)
	at redis.clients.jedis.Jedis.hget(Jedis.java:622)

Everything worked fine until recent. Could you suggest what's happening?

**Comment by marcosnils** [comment] 2017-01-08 19:07
@inponomarev this has been discussed extensively in the mailing lists and GH issues. Please refer to those sources to better diagnose your problem and find possible fixes

**Comment by inponomarev** [comment] 2017-01-21 21:27
@marcosnils, thanks for your answer, I ran through all the web pages with 'cannot be cast to [B' phrase. I updated to 2.9.0. I use JedisPool and .close() in 'finally' block to return connections. I use setTestOnBorrow(true) in JedisPool configuration. Still the problem occurs from time to time. 

I do admit it might be my fault, but the problem is that 'something cannot be cast to [B' message is not informative and it does not help to diagnose the issue. And as far as we can see from Google search, the same message puzzles many people. Maybe something could be done with this? Can it be more informative?

**Comment by ogasawaraShinnosuke** [comment] 2017-07-03 08:56
pom.xml
``` xml
<dependency>
<groupId>redis.clients</groupId>
<artifactId>jedis</artifactId>
<version>2.9.0</version>
</dependency>
```

When extracting from the LIST type, it is trying to convert it to the LONG side why.

``` java
Jedis jedis = // get Jedis instance
String cacheKey = "key";
Long len = jedis.llen(cacheKey);
if (len == null || len < 1) List<String> list = jedis.lrange(cacheKey, 0, len);
```

``` java
due to exception [java.lang.Long cannot be cast to java.util.List]
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:269) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Jedis.lrange(Jedis.java:935) ~[jedis-2.9.0.jar:?]
```

I do not know if it relates to this issue, if you know who caused the problem, would you please teach me?

**Comment by ogasawaraShinnosuke** [comment] 2017-08-18 15:22
Does anyone know about the above matter?

**Comment by inponomarev** [comment] 2017-08-19 09:20
I had to investigate the issue myself debugging through Jedis code.

This issue occurs when Jedis receives an unexpected answer from Redis server, e. g.: Jedis tries to GET a value and expects binary answer, but instead it receives an integer from TTL call made by someone else.

The most probable cause is that one Jedis object is shared **between multiple threads**. Check your code thoroughly for this. But from time to time these problems occur **with no visible cause.** I use
         
    poolConfig.setTestOnBorrow(true);
    poolConfig.setTestOnCreate(true);

This forces Jedis to call PING every time the connection is requested from pool and in case this exception occurs, just reconnect. This seems to me like suppressing the real problem. **There is a problem with Jedis**. At least something can be done to make 'Foo cannot be cast to Bar' exception more informative.

**Comment by ogasawaraShinnosuke** [comment] 2017-08-19 13:20
I saw https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment and wrote below code.

``` java
try (Jedis jedis = pool.getResource()) {
// jedis actions
}
```

**Comment by yhari** [comment] 2017-12-18 16:17
Facing same issue as @inponomarev.  Version 2.9.0. Happens with certain level of concurrency. It happens very intermittently and I couldn't replicate

**Comment by sazzad16** [comment] 2018-01-21 14:07
First of all, I have no idea about lua. Please do correct me if I'm wrong.

@mayankdang From your code:

``` lua
if condition_1 then
    if condition_2 then
        return
    else
        return
    end
end --> no else, no return
```

it seems like it's possible that the script would return nothing. So Response object of evalsha is trying to consume something which is actually the return of next command, del (which is Long). In that case, your exception is very much possible at 

https://github.com/xetorthio/jedis/blob/7cc1197b09eab38d5951d2e95e7902fa406bffb6/src/main/java/redis/clients/jedis/BuilderFactory.java#L56

@HeartSaVioR @nykolaslima @marcosnils WDYT?

**Comment by marcosnils** [comment] 2018-01-21 14:34
@sazzad16 according to the example in the first post, the lua script always returns a value. @HeartSaVioR said that this was fixed in the master branch.

**Closed** 2018-01-21 14:35 UTC
Labels: DISCUSSION NEEDED

**Comment by sazzad16** [comment] 2018-01-21 14:44
@marcosnils I was also considering that

> The error doesn't come if the lua script is modified to _(return any constant string)_

However, it's closed :)
