### ISSUE TITLE
Caused by: java.net.SocketException: Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by welyss** [xetorthio/jedis#906] opened 2015-03-06 06:41 UTC
when write 50w data(something like:a hashmap includes 50w row) to redis server,it works.
but when i write 55w data to redis server,this exception has been throwed.
at first,i think it's caused by timeout,but i set maxtimewait from 1000*1000 to -1, it also doesn't work.
then i think there is not enough memery,but i change env to my local, my local mem is 8g,and redisconf's [maxmemory] is default not be set,so i think the problom is not here,
at last,i have changed env to my local,and it also doesn't work,so i think the reason is not on server,it maybe client's problem,i really can't not understand why it doesn't work.help!

jedis version is:2.2.1,(2.6.0 also)
redis info:
# Server
redis_version:2.8.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:c727d0517b021f2
redis_mode:standalone
os:Linux 2.6.32-431.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.7
process_id:2852
run_id:0294dde7a8ea2b23ddd86069d62752a0a33
tcp_port:6379
uptime_in_seconds:12528
uptime_in_days:0
hz:10
lru_clock:2050369
config_file:/usr/local/redis/conf/redis.co

# Clients
connected_clients:7
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:9235096
used_memory_human:8.81M
used_memory_rss:17690624
used_memory_peak:80723800
used_memory_peak_human:76.98M
used_memory_lua:33792
mem_fragmentation_ratio:1.92
mem_allocator:jemalloc-3.2.0

# Persistence
loading:0
rdb_changes_since_last_save:1
rdb_bgsave_in_progress:0
rdb_last_save_time:1425595531
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok

# Stats
total_connections_received:192
total_commands_processed:892515
instantaneous_ops_per_sec:0
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:6
evicted_keys:0
keyspace_hits:3559
keyspace_misses:188
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:12960

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:141.56
used_cpu_user:32.85
used_cpu_sys_children:1.75
used_cpu_user_children:3.52

# Keyspace
db0:keys=21715,expires=18,avg_ttl=20991829

**Comment by lquterqtd** [comment] 2015-05-11 06:52
i met the problem the same, moore of 500 thousands of data in hashmat write failed with exception
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer: socket write error
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:94)
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:74)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:78)
	at redis.clients.jedis.BinaryClient.hmset(BinaryClient.java:242)
	at redis.clients.jedis.Client.hmset(Client.java:158)
	at redis.clients.jedis.Jedis.hmset(Jedis.java:631)
	at com.axon.scene.RedisHmsetTest.main(RedisHmsetTest.java:114)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
	at redis.clients.util.RedisOutputStream.write(RedisOutputStream.java:53)
	at redis.clients.util.RedisOutputStream.write(RedisOutputStream.java:44)
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:90)
maybe the buffer in RedisOuputStream is full, default is 8K,nor do i know the sulotion to solve it .

**Comment by marcosnils** [comment] 2015-05-11 14:37
@lquterqtd @welyss any chance you can share a snippet that reproduces the error?

**Comment by lquterqtd** [comment] 2015-05-11 14:45
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import redis.clients.jedis.Jedis;

import com.axon.scene.common.RedisPool;
import com.google.gson.Gson;

public class RedisHmsetTest {
    public static class DataModel {
        private int cid = 0;
        private List<TTMap> map = new ArrayList<TTMap>();
        
        public List<TTMap> getMap() {
            return map;
        }
        public void setMap(List<TTMap> map) {
            this.map = map;
        }
    }

    public static class TTMap {
        private int tid;
        private long tm;
        
        public long getTm() {
            return tm;
        }
        public void setTm(long tm) {
            this.tm = tm;
        }
        public TTMap(int tid, long tm) {
            this.tid = tid;
            this.tm = tm;
        }
    }
    
    public static void saveHashmap(Map<String, String> savedStrategy) {
        Jedis jedis = null;
        Map<String, String> tempSavedStrategy = new HashMap<String, String>();
        int cnt = 0;
        try {
            jedis = RedisPool.getJedis();
            for (Map.Entry<String, String> entry : savedStrategy.entrySet()) {
                tempSavedStrategy.put(entry.getKey(), entry.getValue());
                cnt++;
                
                if (cnt >= 500000) {
                    jedis.hmset("RedisHmsetTest", tempSavedStrategy);
                    tempSavedStrategy.clear();
                    cnt = 0;
                }
            }
            
            if (cnt > 0) {
                jedis.hmset("RedisHmsetTest", tempSavedStrategy);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            RedisPool.returnResource(jedis);
        }
    }
    
    public static void main(String[] args) throws UnsupportedEncodingException {
        long pCnt = 2500000L;
        int tCnt = 4;
        Gson gson = new Gson();
        
        long t1,t2,t3,t4,t5;
        
        Map<String, String> sttg = new HashMap<String, String>((int) pCnt);
        Map<Long, DataModel> rsttg = new HashMap<Long, RedisHmsetTest.DataModel>();
        
        long tm = System.currentTimeMillis() / 1000;
        
        t1 = System.currentTimeMillis();
        
        for (long p=100001569758007822L; p<100001569758007822L+pCnt; p++) {
            DataModel d = new DataModel();
            for (int t=180000; t<180000+tCnt; t++) {
                d.getMap().add(new TTMap(t, tm + t));
            }
            
            sttg.put(String.valueOf(p), gson.toJson(d, DataModel.class));
        }
        
        t2 = System.currentTimeMillis();
        System.out.println(String.format("generate %d items to sttg use %d ms", pCnt, t2 - t1));
        
        Jedis jedis = null;
        try {
            jedis = RedisPool.getJedis();
            System.out.println(jedis.hmset("RedisHmsetTest", sttg));
            
            t3 = System.currentTimeMillis();
            System.out.println(String.format("write %d items from sttg use %d ms", sttg.size(), t3 - t2));
            
            Map<String, String> mm = jedis.hgetAll("RedisHmsetTest");
            
            t4 = System.currentTimeMillis();
            System.out.println(String.format("read %d items from sttg use %d ms", mm.size(), t4 - t3));
            
            for (Map.Entry<String, String> entry : mm.entrySet()) {
                rsttg.put(Long.valueOf(entry.getKey()), gson.fromJson(entry.getValue(), DataModel.class));
            }
            
            t5 = System.currentTimeMillis();
            System.out.println(String.format("load %d items to rsttg use %d ms", mm.size(), t5 - t4));
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            RedisPool.returnResource(jedis);
        }
    }
}

i used the JedisPool with the default configuration except the timeout, what is like below:
new JedisPool(config, ProcessConfig.getInstance().getProperty("redisIp"), Integer.valueOf(ProcessConfig.getInstance().getProperty("redisPort")), 60 * 1000);

import java.io.IOException;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;

public class RedisPool {
    private static JedisPool pool = null;
    
    public static synchronized Jedis getJedis() throws NumberFormatException, IOException {
        if (pool == null) {
            JedisPoolConfig config = new JedisPoolConfig();
            
            pool =  new JedisPool(config, ProcessConfig.getInstance().getProperty("redisIp"), Integer.valueOf(ProcessConfig.getInstance().getProperty("redisPort")), 60 * 1000);
        }
        
        return pool.getResource();
    }
    
    public static synchronized void returnResource(Jedis jedis) {
        if (jedis != null) {
            pool.returnResource(jedis);
        }
    }
}

**Comment by HeartSaVioR** [comment] 2015-05-11 14:52
@lquterqtd 
Thanks for sharing!
Seems like you doesn't handle connection exception while returning instance to Pool.
Did you set timeout to Redis configuration? It means that Redis will disconnect connections with idle timeout.

**Comment by marcosnils** [comment] 2015-05-11 14:54
@lquterqtd by just looking at the code I see that you're not handling exceptions correctly. Instead of calling `returnResource` in the `finally` block you need to use `jedis.close()`. The exception you're getting is due to redis closing the connection (possibly because of it's idle). 

Do you have the `timeout` configuration parameter set in redis?

**Comment by lquterqtd** [comment] 2015-05-11 15:04
@HeartSaVioR @marcosnils 
do you mean the timeout configuration on the server? 
i used the default "timeout 0".
in the exception block i should use returnBrokenResource method?
i don't think i need to use jedis.close() in the finally block.  returnResource is just enough.

**Comment by marcosnils** [comment] 2015-05-11 15:05
@lquterqtd `returnResource` and `returnBrokenResource` are deprecated in 2.6 and 2.7. You need to use `jedis.close()` in the finally block.

**Comment by lquterqtd** [comment] 2015-05-11 15:17
<dependency>
        <groupId>redis.clients</groupId>
        <artifactId>jedis</artifactId>
        <version>2.6.2</version>
        <type>jar</type>
        <scope>compile</scope>
</dependency>
i used 2.6.2 and i mentioned the source code, jedis.close() is implemented:
@Override
  public void close() {
    if (dataSource != null) {
      if (client.isBroken()) {
        this.dataSource.returnBrokenResource(this);
      } else {
        this.dataSource.returnResource(this);
      }
    } else {
      client.close();
    }
  }

i did not find the deprecated tag over the  returnResource method.  
@marcosnils  thanks a lot, i read the part of the wiki.i will try later.

**Comment by marcosnils** [comment] 2015-05-11 18:05
@lquterqtd here are the deprecated methods in 2.6 and 2.7 respectively

https://github.com/xetorthio/jedis/blob/2.7/src/main/java/redis/clients/jedis/JedisPool.java#L104-L119
https://github.com/xetorthio/jedis/blob/2.6/src/main/java/redis/clients/jedis/JedisPool.java#L87-L103

Have you changed your code to use the `close` method? Are you still seeing your issues?

**Comment by marcosnils** [comment] 2015-05-11 18:50
@lquterqtd I just run your code locally and after tuning the JVM Heap and GCOvearHeadLimit it passed without problems. I used redis 2.8.19 and Jedis 2.6.3. 

It took a while to complete but I didn't get any exception. I used a redis server with the default configuration.

Looking at your stacktrace seems like redis is closing the connections for some reason. I'd recommend setting your redis logs to "FINE" and see if it complains there. 

Another thing to notice is that the way you're calling hmset is not optimal in terms of memory and performance because you're basically generating a  huge stream chunk and sending all the data to redis at once. I'd recommend using pipeline and batching the inserts to reduce the memory footprint and improve the insertion times.

**Comment by marcosnils** [comment] 2015-05-11 20:49
@antirez is there a max limit in terms of key - value paris that `hmset` can handle?. @lquterqtd is trying to hmset 5M items (keys + values) in a single redis operation and for some reason as soon as Jedis is starting to write into the socket we get a `Broken pipe` exception which I've confirmed is redis closing the client connection.

I have checked and the query buffer limit (http://redis.io/topics/clients#query-buffer-hard-limit) is not being reached. I've also set the loglevel to DEBUG and I see redis disconnecting the client before getting the exception from the java side but it doesn't say anything why it's disconnecting it.

**Comment by marcosnils** [comment] 2015-05-11 21:47
@antirez @lquterqtd @HeartSaVioR just reproduced it making a simple python / telnet program.

if you set the `total` variable any number higher than 524287 you'll get the Broken pipe error. 

I guess this might be some redis/os limit we're hitting. I've tried looking in the redis documentation but I didn't find anything about it. 

```python
import telnetlib

start = 100001569758007822
value = '{"cid":0,"map":[{"tid":180000,"tm":1431560060},{"tid":180001,"tm":1431560061},{"tid":180002,"tm":1431560062},{"tid":180003,"tm":1431560063}]}'

total = 2500000

redis_total = total * 2 + 2


tn = telnetlib.Telnet("localhost", 6379)
tn.write("*"+str(redis_total)+"\r\n$5\r\nHMSET\r\n$14\r\nRedisHmsetTest\r\n")

for x in range(start, start + total ):
    key = str(x)
    tn.write("$"+str(len(key))+"\r\n")
    tn.write(key)
    tn.write("\r\n")
    tn.write("$"+str(len(value))+"\r\n")
    tn.write(value+"\r\n")

print tn.read_some()

tn.close()

```

**Comment by itugs** [comment] 2015-05-12 00:35
@lquterqtd @marcosnils 
This is not about connection but about limitation of multibulk size.
Redis restrict maximum size of multibulk as (1024 * 1024).

https://github.com/antirez/redis/blob/unstable/src/networking.c#L1023-1027
I could confirm this by tcpdump.
```
09:17:27.740553 IP localhost.53053 > localhost.6379: Flags [P.], seq 1:8191, ack 1, win 12759, options [nop,nop,TS val 404996303 ecr 404994609], length 8190
E. 2..@.@............=..0....9mX..1..'.....
.#...#.1*1048578  <---- exceed limitation
$5
HMSET
$14
RedisHmsetTest
$18
100001569758228599
$18

09:17:27.740797 IP localhost.6379 > localhost.53053: Flags [P.], seq 1:48, ack 8191, win 12503, options [nop,nop,TS val 404996303 ecr 404996303], length 47
E..cg.@.@..............=.9mX0.:...0..W.....
.#...#..-ERR Protocol error: invalid multibulk length  <-- protocol error

... omitted ...

09:17:27.740865 IP localhost.6379 > localhost.53053: Flags [R], seq 238644616, win 0, length 0
E..(..@.@..............=.9m.....P.......  <-- RST
```
So in this case, limitation of max key/value pair if 524288, (1024*1024) / 2.

I thought two action items from this
1. Check multibulksize before write to output stream. Maybe `Protocol.sendCommand` is good point.
2. From tcpdump Redis send RESP Errors before reset connection. So in erronouse case, we can check intput stream to show reason of error. 

If agreed, I'll send PR for these.

**Comment by marcosnils** [comment] 2015-05-12 00:45
@itugs thanks for the investigation, do you know if that is documented somewhere in the redis docs?, I couldn't find it. @HeartSaVioR realized that if you use the "VERBOSE" logevel you can see the error in redis logs (weird that in DEBUG it doesn't show up, @antirez is this possible?).

@itugs regarding to your propositions I believe i'd only do number 2 so if redis limitation changes in the future we don't need to change anything from the Jedis side.  What do you think?

**Comment by HeartSaVioR** [comment] 2015-05-12 00:52
I posted strange logging behavior to Redis repo.

**Comment by itugs** [comment] 2015-05-12 01:00
@marcosnils No I could not found any docs about that. As you said I check tcpdump because I could not see any log from redis log. And even "VERBOSE" we can not see specific reason of error, like `invalid multibulk length`. I think it's better to print out specific reason to redis log, but I don't know if this is spec.

About propositions, yes I agree with you. If number two is done, number one is not a big deal. About number 1, I wanna hear the reason of that limitation. @antirez could you tell us about the number?

**Comment by HeartSaVioR** [comment] 2015-05-12 01:06
I made a patch to fix strange log behavior.
https://github.com/antirez/redis/pull/2573

**Comment by marcosnils** [comment] 2015-05-12 02:54
@lquterqtd can we close this issue now?

**Comment by lquterqtd** [comment] 2015-05-12 05:19
@marcosnils i just read the @itugs investigation, the problem is that in server side multibulk size is limit to 1024*1024, is that right?
I will use pipeline or batch inserts to have a try.

**Closed** 2015-05-25 04:37 UTC

**Comment by merishav** [comment] 2016-06-15 12:58
See if your redis is running in protected mode, disable the protected mode
