### ISSUE TITLE
@sazzad16 why close me issues?

### ISSUE THREAD

**Issue by startjava** [xetorthio/jedis#2111] opened 2019-12-03 01:08 UTC
https://github.com/xetorthio/jedis/issues/2110
https://github.com/xetorthio/jedis/issues/2109

The purpose of the two issues I published was to ask Jedis officially, which version will be implemented in the future, rather than shutting down my issues directly, and no answer, which made me angry, and several of the releases I published were not implemented in future version plans. Our requirements are just that Jedis need a relatively complete implementation of the Redis API, and this is only the most basic Jedis user requirements.

@sazzad16

**Comment by sazzad16** [comment] 2019-12-03 02:18
@startjava Each of the closed issues has a comment stating the reason. If there is anything to ask about those comments, please ask in respective issues. Thanks!

In case you don't understand, both of the mentioned issues are duplicates of already existing issues created by none other than you.
- #2110 is a duplicate of #2073 
- #2109 is a duplicate of #2081

**Closed by sazzad16** 2019-12-03 02:18 UTC

**Comment by sazzad16** [comment] 2019-12-03 02:29
@startjava Just to clarify,

> Our requirements are just that Jedis need a relatively complete implementation of the Redis API,

1. Whom are you referring exactly by **Our**?

2. What are your contributions towards fulfilling your requirements (other than creating Github issues)?

3. What are you willing to do or provide to complete Redis API implementation in Jedis?
