### ISSUE TITLE
Redis keys are missing when creating concurrently

### ISSUE THREAD

**Issue by Unnamalai57** [xetorthio/jedis#2011] opened 2019-06-28 05:55 UTC
using jedis client 
try (Jedis jedis = RedisConnection.getJedisPool().getResource()) {
				if (!jedis.exists(key)) {
					jedis.hmset(key, map);
					jedis.expireAt(key, time);
				}
		} 
creating keys. Per minute I have to create 83 keys concurrently. And read values from redis and push the values to mysql database. After pushing the values the keys will be deleted in redis.

When I checked the counts of records created in mysql was 82 , sometimes 80 and sometimes 83. I could not predict  how  the keys are missing.

 Redis / Jedis Configuration

 Jedis dependency 
                 <groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>2.9.0</version>

Redis version:
           redis-cli 5.0.3
Java version:
          java 8

could you please tell me to fix this issue?

**Comment by marcosnils** [comment] 2019-06-28 21:20
Doesn't seem like an issue in Jedis. Please provide a **full example** that shows how Jedis loses keys while inserting concurrently. Maybe the problem is your code that inserts into your mysql database.
I'm closing this as there's nothing we can do about it. Please update a proper example "just" with jedis / redis interaction that demonstrates how concurrency is inconsistent.

**Closed by marcosnils** 2019-06-28 21:20 UTC
