### ISSUE TITLE
jedis Concurrent Downgrade

### ISSUE THREAD

**Issue by Lucent-Wong** [xetorthio/jedis#1117] opened 2015-09-17 07:08 UTC
Hello,

I am the new to redis and jedis. 

I have set up 50 threads to get value from jedis, there got some performance down grade(nearly 1%), which cost more than 10ms.

But the it performs well when the concurrency is low, which all the time cost are less than 5ms.
And the redis-benchmark also got great performance.

The ping from my client to server is about 1.5ms. Any one got the experience to solve similar problem?

**Comment by marcosnils** [comment] 2015-09-23 11:19
@Lucent-Wong any chances you can provide a reproducible scenario?. Many users are running Jedis in production today and they don't experience performance downgrade problems.

**Comment by Lucent-Wong** [comment] 2015-09-24 02:41
@marcosnils sure, the following is my test code:

import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;

import java.lang.Thread;
import java.lang.Runnable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class BenchMark {
	public static JedisPool jedisPool;
	public static JedisPoolConfig jedisPoolConfig;
	public static int loop;
	public static int threadsNum;
	public static String key;
	public int id = 0;

	public static void main(String[] args) {
		BenchMark benchMark = new BenchMark();
		benchMark.test(args);
	}

	public void test(String[] args) {
		int maxActive = Integer.valueOf(System.getenv("MAX_ACTIVE"));
		int maxIdle = Integer.valueOf(System.getenv("MAX_IDLE"));
		int minIdle = Integer.valueOf(System.getenv("MIN_IDLE"));
		String hostIP = args[3];
		jedisPoolConfig = new JedisPoolConfig();
		jedisPoolConfig.setMaxTotal(maxActive);
		jedisPoolConfig.setMaxIdle(maxIdle);
		jedisPoolConfig.setMinIdle(minIdle);
		jedisPoolConfig.setTestWhileIdle(false);

		jedisPool = new JedisPool(jedisPoolConfig, hostIP, 6379, 2000, "password", 1);
		threadsNum = Integer.valueOf(args[0]).intValue();
		loop = Integer.valueOf(args[1]).intValue();
		key = args[2];

		System.out.println("threads = " + threadsNum);
		System.out.println("loop = " + loop);
		System.out.println("key = " + key);

		ExecutorService executor = Executors.newCachedThreadPool();
		for (int i=0; i<threadsNum; i++)
		{
			JedisThread jt = new JedisThread();
			executor.execute(jt);
		}
		executor.shutdown();
	}

	public class JedisThread implements Runnable {
		private int tid;
		public JedisThread() {
			tid = id++;
		}
		public void run() {
			 for(int i = 0; i<loop; i++){
				 long start = System.currentTimeMillis();
				 Jedis jedis = jedisPool.getResource();
				 long end0 = System.currentTimeMillis();
				 jedis.get(key);
				 jedis.close();
				 long end1 = System.currentTimeMillis();
				 int idle = jedisPool.getNumIdle();
				 int active = jedisPool.getNumActive();
				 System.out.println("id_" + tid + "_Total:\t" + (end1-start) + "\tgetJedis:\t" + (end0-start) + "\tgetKey\t" + (end1-end0) + "\tidle=\t" + idle + "\tactive=\t" + active );
				 }
		}
	}
}

and use the following script to run the job, could be run like:
"./runBenchmark.sh ${REDIS_SERVER_DOMAINNAME}"


#!/bin/bash

#filename:runBenchmark.sh
export MAX_ACTIVE=500;
export MAX_IDLE=500;
export MIN_IDLE=50;

IP=`nslookup $1 | grep "Address: "`
IP=${IP#* }
echo "$IP"
#50 threads, each thread run with 10000 loops to "get"
time java -Djava.ext.dirs=./ BenchMark 50 10000 "key" ${IP} > temp
cat temp  | grep "getKey" | awk -F "\t" '{a[$2]+=1}END{for (i in a){print i "\t" a[i]}}' | sort -n


And the following is the data I have got, in which there are more than 400(nearly 0.1%) response cost more than 10ms, I think it maybe caused by the NetIO blocking:
real    0m18.644s
user    0m12.061s
sys     0m22.409s
1       227785
2       266858
3       3379
4       893
5       244
6       166
7       95
8       49
9       25
10      7
11      2
12      5
13      1
23      1
24      15
25      5
26      5
27      6
28      7
29      18
30      40
31      38
32      23
33      15
34      19
35      21
36      11
37      6
38      3
41      1
42      3
43      6
44      19
45      13
46      1
48      13
49      12
50      6
51      30
52      46
53      30
54      14
55      4
201     1
202     2
203     2

**Comment by allanwax** [comment] 2015-09-29 18:56
One of the things I do in production is to _warm up_ all the connections before doing any real work.  Then as connections are pulled from the pool there is a high probability that no work will have to be extended to actually make the connection.  It'll just use one from the pool that's already open.  Given you have 'max connections', make that many requests before closing the connections.  In production we never actually use the max all the time and in reality it goes to some steady state number of open connections.

So I suggest that you change your test to first warm all the connections up and then test, and see if that makes a difference.

Also be aware that it also costs to make the measurements.  You may want to have a separate run that does everything _but_ the actual Jedis calls and subtract that from the results you get.

You may also want to change the testing technique use use `invokeAll` and see what the numbers are there.

**Comment by Lucent-Wong** [comment] 2015-09-30 02:52
Hi @allanwax thank your advices. 

Actually, I have excluded the time costs of getResource from the pool. And according to the statistical data, the performance of Jedis can meet my demandes. But once I use it in my production, which runs in Tomcat, it does not work very well. The NetIO always blocked although there are only 150 redis calls per second, is there any experience you can share? Thank you very much.

**Comment by allanwax** [comment] 2015-09-30 16:46
Without knowing details, here are some things that may, or may not, affect the NIO performance.

- Check the profile on your Linux box for whichever userid runs the Tomcat app.  Change it to max out the number of open connections; this has nothing to do with redis connections.
- Redis is currently single threaded (Antirez is working on multi-threaded) so only one connection is active at a time.  Some Redis operations are more expensive than others and therefore block longer.  Would a {{pipeline}} help.
- Consider using a {{redis cluster}} instead of a single redis instance.  By using a cluster the keys are spread around and thus more instances of redis can be operating simultaneously, as a separate connection to the instance that holds the key being worked on.  This is not a panacea since if you use multi key operations there are restrictions on what you can do.
- *Never* use the {{KEYS}} command to get a list of keys matching some pattern.  Instead use {{SCAN}} which allows you to search in chunks and thus you free the connection between scans for other requests.  I can give you some scan based code if you need it.
- Consider not using Tomcat but starting your own standalone Jetty server instance for the applications.  This way your not fighting anything else's resource usage.

That's all I can think of off the top of my head.  I hope some of these help you.

**Comment by EdwardLee03** [comment] 2015-09-30 17:19
I agree with using **Redis Cluster for multiple instances** for @allanwax suggestion.
@Lucent-Wong , you do not call `jedis.close();` in JedisThread, you should call `jedisPool.returnResource(jedis);` . You can click [ShardedJedis for Wiki](https://github.com/xetorthio/jedis/wiki/AdvancedUsage#shardedjedis) to see detail usage.

**Comment by allanwax** [comment] 2015-09-30 17:58
To be clear, I am recommending `redis cluster` which is now a released product (redis 3.0.4 ? ) and not `sharded redis` of which there are many different implementations.

**Comment by allanwax** [comment] 2015-09-30 18:03
Regarding running the war file by itself, see https://webtide.com/jetty-runner/

**Comment by HeartSaVioR** [comment] 2015-10-01 21:19
@Lucent-Wong 
You can use contiperf to benchmark with set warmup, test interval, concurrent threads, and so on.
Please refer https://github.com/HeartSaVioR/jedis-benchmark.
You can fork it and modify to use JedisPool, and test with multi thread.

**Comment by marcosnils** [comment] 2015-10-05 21:29
@Lucent-Wong do you have any updateS?

**Comment by Lucent-Wong** [comment] 2015-10-06 16:01
@marcosnils I think jedis can meet my performance requirement, I am try to figure out why it will be slow in my production which runs in Tomcat

**Comment by Lucent-Wong** [comment] 2015-10-06 16:02
@allanwax @HeartSaVioR Thank you for your advices

**Comment by marcosnils** [comment] 2015-10-06 16:15
@Lucent-Wong. Perfect.

It'd be nice if you could provide a reproducible scenario (maybe a docker container?). Showing the performance difference so we can assist. I'm closing this issue for now, please open a new one if you find anything on the tomcat thing.

**Closed by marcosnils** 2015-10-06 16:15 UTC

**Comment by lzw88** [comment] 2015-10-07 05:40
hi marcosnils,
 
 2015-09-29 06:55:46 [com.my.rtuserver.output.service.DatacenterClientThread]-[ERROR] 
 redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnResourceObject(Pool.java:54)
	at redis.clients.jedis.ShardedJedisPool.returnResource(ShardedJedisPool.java:53)
	at redis.clients.jedis.ShardedJedisPool.returnResource(ShardedJedisPool.java:14)
	at com.my.datacenter.cache.conn.impl.ShardControlImpl.freeConnection(ShardControlImpl.java:77)
	at com.my.datacenter.cache.conn.impl.ShardControlImpl.addHash(ShardControlImpl.java:480)
	at com.my.datacenter.cache.handle.impl.MYCacheTableImpl.PaddHash(MYCacheTableImpl.java:587)
	at com.my.datacenter.cache.handle.impl.MYCacheTableImpl.addHash(MYCacheTableImpl.java:574)
	at com.my.rtuserver.output.service.DatacenterClientThread.execute(DatacenterClientThread.java:192)
	at com.my.rtuserver.output.service.DatacenterClientThread.run(DatacenterClientThread.java:50)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalStateException: Returned object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:537)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:52)
	... 11 more

My program worked on jedis 2.4.2 and 2.5.2 in IDC to encounter above error.
  I found  this problem  about issue #560 and #554,but i don't find which jedis version to fix issue?  i which verison to download  if i want to slove it. 
    thank you.

**Comment by marcosnils** [comment] 2015-10-07 06:33
@lzw can you please open a new issue so se csn track the problemas better?

In addition it'd be nice if you could share a code snippet that shows how to reproduce the problem you're seeing.

Also, please add which Jedis/Jedis versions you're using

**Comment by lzw88** [comment] 2015-10-07 14:11
@marcosnils I am using 2.5.2 versions

**Comment by marcosnils** [comment] 2015-10-07 14:16
@lzw88 please do what I posed above. Open a new issue and put all the info there.
