### ISSUE TITLE
Multi get operations on redis cluster where hash tags can't work

### ISSUE THREAD

**Issue by sandeepd-bsb** [xetorthio/jedis#1293] opened 2016-05-23 13:52 UTC
So, I guess this one's been around for some time. Redis cluster doesn't support multi-key ops... while hash tags are suitable and work perfectly for most of the use cases, it doesn't work with our specific problem. I can assure a certain key belongs to a particular hash slot using the `{}` but while querying multiple keys, I cannot assure they will belong to the same one.

So firstly my question is what is the rationale behind not providing such an implementation on the server? I'm sorry that that's redis particularly, but I guess I can still put it here ;-) and if not, why doesn't jedis (as of 2.8.1) provide such an implementation - where it can query over multiple nodes in the cluster, aggregate and deliver the result. Any limitations, or is it in the pipeline?

#### Jedis version:
2.8.1
#### Redis version:
3.2
#### Java version:
1.8

**Comment by marcosnils** [comment] 2016-05-23 13:56
Dupe of https://github.com/xetorthio/jedis/issues/990

**Closed by marcosnils** 2016-05-23 13:56 UTC

**Comment by sandeepd-bsb** [comment] 2016-05-23 14:17
@marcosnils thanks for pointing to a more generic discussion that was quite informative. However, is there any conclusion on providing support for such multi-key ops? On the other hand, is it advisable to use `JedisClusterConnectionHandler` to get the list of nodes and perform ops on them individually and aggregate ourselves?

**Comment by marcosnils** [comment] 2016-05-23 14:21
> there any conclusion on providing support for such multi-key ops?
Nope. We still haven't decided how to implement this. Usually clients are handling it on their side. 



> is it advisable to use JedisClusterConnectionHandler to get the list of nodes and perform ops on them individually and aggregate ourselves?

you can safely use jc.getClusterNodes() https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/BinaryJedisCluster.java#L61-L63

**Comment by sandeepd-bsb** [comment] 2016-05-23 14:23
Great, thanks @marcosnils !

**Comment by marcosnils** [comment] 2016-05-23 14:30
@sandeepd-bsb you're welcome to leave your opinion in the discussion thread.
