### ISSUE TITLE
Jedis socket settings causing issues under load ?

### ISSUE THREAD

**Issue by janssk1** [xetorthio/jedis#1322] opened 2016-06-23 21:07 UTC
While under load, we have noticed that some jedis connections raise unexpected exceptions such as 'classcastexception' and 'numberformatexception' while running redis operations. These error can occur if multiple threads acces the same Jedis instance, but this is not the case for us. 

The scenario we have seen is that some connections (we use a pool of connections) raise a timeout to an operation (eg zcore). As a result we close that connection and remove it from the pool. 
To handle new load, a new connection is created (new jedis instance, probably using the same local port), and that new instance seems to receive some of the responses that where meant for the 'old' connection. 

This is normally not possible with TCP, but is is possible with the sockets created by Jedis: 

socket.setReuseAddress(true);
        socket.setKeepAlive(true); // Will monitor the TCP connection is
        // valid
        socket.setTcpNoDelay(true); // Socket buffer Whetherclosed, to
        // ensure timely delivery of data
        socket.setSoLinger(true, 0); // Control calls close () method,

I have no strong evidence that the socket settings are the root cause of the problems we occasionally see but I wonder why client connections have all these fancy settings. Most literature i find on the internet does not recommend messing with these, especially the reuseAddress & linger settings. 
#### Jedis version:

1.8.1
#### Redis version:

3.0.7

**Comment by sheinbergon** [comment] 2016-07-07 09:20
@janssk1  

Are you implementing your own pool or using Jedis pre-built ones ? 
By connection timeout you mean some form of jedis exception  or socket timeout ?
How are you closing the connection ? How are you re-instantiating a new one ? 
Can you provide means of reproducing ?


I myself have  been using Jedis object pools in a highly concurrent environment ( doznes of servers , each sending 1000 of requests per second )  and encountered no such issues , so this scenario intrigues me

**Comment by sazzad16** [comment] 2017-11-22 04:57
Closing due to inactivity.

**Closed by sazzad16** 2017-11-22 04:57 UTC
Labels: COULD NOT REPRODUCE
