### ISSUE TITLE
Jedis has Not Been Released Since 2016

### ISSUE THREAD

**Issue by kmeurer** [xetorthio/jedis#1851] opened 2018-08-15 14:06 UTC
As far as I can tell, Jedis has not been released since September 2016, despite a significant amount of code being contributed to the repository (~700 commits).

Are there plans to release a new version of Jedis to get these contributions in the hands of end-users?

**Comment by marcosnils** [comment] 2018-08-15 14:08
Dupe of #1658

**Closed by marcosnils** 2018-08-15 14:08 UTC
