### ISSUE TITLE
Tests don't pass in OSX

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#1370] opened 2016-08-18 23:48 UTC
Module tests don't pass in OSX. It would be amazing if some caritative soul could help to diagnose

@HeartSaVioR :wink: ??

**Comment by gogeof** [comment] 2016-09-10 15:13
Did you read the Makefile? Did you get the redis source first? And did you have stop the firewall first, because the redis need to listen the ports.

**Comment by gogeof** [comment] 2016-09-10 15:14
# But, in fact, I am also get some errors.
...   
- Tests run: 476, Failures: 3, Errors: 11, Skipped: 0

**Comment by marcosnils** [comment] 2016-09-10 15:16
@gogeof it's something about the module test, but I dont have an osx system to diagnose

**Comment by gogeof** [comment] 2016-09-10 15:21
You means you have try run mvn test in the other system, and it all gets pass?

**Comment by marcosnils** [comment] 2016-09-10 15:36
Yes, in Linux all tests pass

sent from mobile

**Comment by gogeof** [comment] 2016-09-10 16:13
# There is a problem about protected-mode.
- by default , protected-mode set yes
- and if I set protected-mode no by manual, solve 5 errors, but get one more failure.
...  
- Tests run: 476, Failures: 4, Errors: 6, Skipped: 0

**Comment by HeartSaVioR** [comment] 2016-09-11 11:35
OK I confirmed protected-mode raises some failures. After disabling protected-mode I don't see any test errors on OSX. (Module test is succeed, maybe its cause was on Redis side.)

@marcosnils @gogeof I re-installed Redis to recent unstable and saw these failures what @gogeof said. I'll create pull request for that, and I think we can close this since it's not happening now.

**Closed** 2016-09-11 11:37 UTC
