### ISSUE TITLE
I use spring data redis and jedis to get score of a zset, but get error sometimes

### ISSUE THREAD

**Issue by afcn007** [xetorthio/jedis#1722] opened 2017-12-21 03:19 UTC
I am using Spring Data Redis 2.0.2. and jedis 2.9.0. The code is

Double device_score = stringRedisTemplate.opsForZSet().score("sset_device_ids", icntvid);
Sometimes, I get this error perhaps 2 - 3 times per day

`
org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [appServlet] in context with path [/adott-api-java] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.NumberFormatException: For input string: "OK"] with root cause
java.lang.NumberFormatException: For input string: "OK"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.valueOf(Double.java:504)
    at java.lang.Double.<init>(Double.java:597)
    at redis.clients.jedis.BinaryJedis.zscore(BinaryJedis.java:1692)
    at org.springframework.data.redis.connection.jedis.JedisConnection.zScore(JedisConnection.java:2385)
    at org.springframework.data.redis.connection.DefaultStringRedisConnection.zScore(DefaultStringRedisConnection.java:1130)
    at org.springframework.data.redis.core.DefaultZSetOperations$22.doInRedis(DefaultZSetOperations.java:313)
    at org.springframework.data.redis.core.DefaultZSetOperations$22.doInRedis(DefaultZSetOperations.java:310)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:152)
    at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:84)
    at org.springframework.data.redis.core.DefaultZSetOperations.score(DefaultZSetOperations.java:310)
    at adott.api.ApiControllerV2.init(ApiControllerV2.java:208)
    at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)`
What is the reason for jedis to throw this error? This seems a jedis bug? Thanks in advanced.

**Comment by marcosnils** [comment] 2017-12-21 16:06
Doesn't seem like a Jedis bug. Looks like something related to spring-data-redis or how you're handling your Jedis connection. Closing as there's to do here unless you can provide a reproducible scenario using Jedis. I'd suggest searching in the spring-data-redis issue tracker to see if someone has seen this already

**Closed by marcosnils** 2017-12-21 16:06 UTC
