### ISSUE TITLE
WATCH not handled correctly for transaction

### ISSUE THREAD

**Issue by yaxing** [xetorthio/jedis#1197] opened 2016-01-20 00:17 UTC
Sample code:

```
Jedis messer =  new Jedis("testhost", testport);
Jedis client = new Jedis("testhost", testport);
try {
            client.watch("test");
            Transaction t = client.multi();
            Response<String> respSet = t.set("key", "value");
            Response<String> respGet = t.get("key");
            messer.set("test", "123"); // mess up watched key
            t.exec();
            System.out.println(respGet.get());
            System.out.println(respSet.get());
} finally {
            messer.close();
            client.close();
}
```

Exception thrown:
``` 
redis.clients.jedis.exceptions.JedisDataException: Please close pipeline or multi block before calling this method.
```

This shall be handled properly and tell user the transaction got discarded due to watched keys changed, instead of throwing a data exception telling that PIPELINE is not closed.

**Comment by marcosnils** [comment] 2016-01-20 00:27
@yaxing this is a duplicate of #1183. The same condition is being triggered on both scenarios.

**Closed by marcosnils** 2016-01-20 00:27 UTC
