### ISSUE TITLE
Release plan for 2.10 or 3.0?

### ISSUE THREAD

**Issue by bobpskier** [xetorthio/jedis#1658] opened 2017-11-16 00:08 UTC
I see the current jedis released version is 2.9 from 2016. I see a 2.10 branch and the master branch looks like it is set prepping for a 3.0 release. I believe there is a fix committed for issue 1424 (https://github.com/xetorthio/jedis/issues/1424) made since the 2.9 release that I'd like to to be able to take advantage of. Is there a recommendation for which version I should pull that contains this fix? Are there future release plans? Thanks.

**Comment by mp911de** [comment] 2017-11-16 09:27
Related to #1576. 

It would be a decent move to get a new release especially considering the number of changes that piled up since the last release. Upgrading from 2.9 to 2.10 might be already an exercise that comes with a few downstream tasks for projects. There are also a few new jedis releases available from Maven Central that were published as cross-releases by under own group Id's of individual forks.

The whole situation isn't healty for the jedis project as the community already starts to fragment. The community behind jedis is quite vibrant and there is a big momentum in issues and pull requests. However, without a stable support from the maintainers, it's not possible to get jedis releases out.

**Comment by sazzad16** [comment] 2018-02-02 06:00
Dupe of #1576

**Closed by sazzad16** 2018-02-02 06:00 UTC
