### ISSUE TITLE
Support mget in ShardedJedis

### ISSUE THREAD

**Issue by zy1984** [xetorthio/jedis#506] opened 2013-12-30 12:25 UTC
If I want to get N keys in ShardedJedis, currently I have to make N get call to achieve this. If it supports mget, then the network call will be reduce to N/n (n is the Sharded instances count)

**Comment by marcosnils** [comment] 2015-05-27 00:49
Right. This a dupe of #471. Let's continue discussion there.

**Closed by marcosnils** 2015-05-27 00:49 UTC
