### ISSUE TITLE
Can't interrupt a thread doing BRPOPLPUSH.

### ISSUE THREAD

**Issue by apennebaker** [xetorthio/jedis#493] opened 2013-12-05 22:50 UTC
I would like to be able to `interrupt()` a thread doing [BRPOPLPUSH](http://redis.io/commands/brpoplpush). Specifically, if nothing has been popped yet, I want `jedis.brpoplpush()` to be able to throw an `InterruptedException`, so the thread can die.

This has been a source of hangs in my program, so for the moment I'm working around this with a manual `while { jedis.rpoplpush(); sleep(); }` that is interruptible.

Specifically, if nothing has yet been popped (e.g., a work queue is empty), it would be good if the command could be interrupted.

**Comment by Grief** [comment] 2015-05-27 13:09
+1 for `InterruptedException`

**Comment by HeartSaVioR** [comment] 2015-05-27 21:52
Hey, Jedis respects Redis command behavior, and there's a timeout so you can make workaround from here. Or maybe pubsub helps you.
IMO it is completely application logic that Jedis doesn't need to include it.

There's long inactivity so for now I'm closing this issue.

**Comment by Grief** [comment] 2015-05-28 08:35
@HeartSaVioR This is _not_ related to Redis but to Java. Using timeout is a sort of busy waiting (http://en.wikipedia.org/wiki/Busy_waiting). If my application completely depends on an appearing of the data in the list, I don't need a timeout. But if I don't specify one, I will not be able to interrupt an operation in any way. For me, it is a major issue. 

Jedis doesn't respect Java guidelines since it doesn't handle Thread.interrupt() correctly.

**Comment by HeartSaVioR** [comment] 2015-05-28 09:52
@Grief I have to say again, if there's some workaround and it fits current situation, why we have to do this?

**Comment by xetorthio** [comment] 2015-05-28 11:36
Hi! So what is the alternative? Can you explain further how BRPOPLPUSH should work?

**Comment by Grief** [comment] 2015-05-28 22:12
@HeartSaVioR if the workaround you are referring to is the using of timeout, I repeat the message - it's a busy waiting. Busy waiting must be avoided.

For example, My application has background thread which reacts on values put it redis list, let's call it 'message queue'. I would like to process this queue as long as my app running. You are proposing the code like following:

`
new Thread("Working thread") {
            @Override
            public void run() {
                connection = jedisConnectionFactory.getConnection();
                while (RUNNING) {
                    byte[] bytes = connection.bRPopLPush(MAGIC_UNNEEDED_TIMEOUT, "SOURCE".getBytes(), "DESTINATION".getBytes());
                    if (bytes == null) continue; // We just do this because we have no other way to interrupt
                    callback(bytes);
                }
                connection.close();
            }
        }.start();
`

Please tell me, what value I need to assign to this `MAGIC_UNNEEDED_TIMEOUT`? 1 second? I must check these bytes for null every second? Please tell me why. 10 seconds? Don't forget that in case of shutting down, the actual shut down could be delayed by up to the specified value. Do I really need to wait for 10 seconds if I just need to shutdown this thread for some reason?

After all of that, please tell me, why cannot I just do this:
`
new Thread("Working thread") {
            @Override
            public void run() {
                connection = jedisConnectionFactory.getConnection();
                while (true) {
                    try {
                        callback(connection.bRPopLPush(0, "SOURCE".getBytes(), "DESTINATION".getBytes()));
                    } catch (InterruptedException e) {
                        log.info("Stopped");
                        break;
                    }
                }
                closeQuetly(connection);
            }
        }.start();
`

**Comment by xetorthio** [comment] 2015-05-28 22:55
Who throws ```InterruptedException``` and how?
Because thread is blocked reading from the socket.

**Comment by HeartSaVioR** [comment] 2015-05-28 22:57
@Grief 
We're implementing BLOCKING Redis DRIVER, not NONBLOCKING.
if you're saying timeout is some kind of busy waiting, all blocking IOs have busy waiting.
Busy waiting's main problem is that It doesn't yield control of CPU and try something. For example, while (true) { ; }
Normally It occupies one core of CPU and core usage is up to 100%.
I don't see this behavior with JDK Socket. So it is not an issue.

And there's PUBSUB if you really need to just read datas and execute sth.

You asked me why you need to present timeout value while you don't need it. 
But how about Jedis? Jedis is no except. Jedis should deal with timeout internally, and problem is getting worse since hard coded timeout cannot fit all of users.

I'm wondering why we take care of all situations including using Jedis to some kind of async way.

**Comment by HeartSaVioR** [comment] 2015-05-28 23:17
@Grief 
For now I'm recommending that you file the issue Java Blocking socket should respect Thread.interrupt() to JCP, Oracle, OpenJDK. 
Since we don't consume InterruptedException, issue can be resolved easily.

**Comment by xetorthio** [comment] 2015-05-28 23:48
Ok. It seems like there is a way.
Please check my reasoning.
`Socket.read` throws `IOException` under certain circumstances.
It seems like it can throw `InterruptedIOException` (which is subclass of `IOException`) when the thread in which the socket is blocked has been interrupted.
If this is true, we could catch `InterruptedIOException` and just throw it instead of throwing a generic `JedisConnectionException`.
Would that solve the problem?

**Comment by HeartSaVioR** [comment] 2015-05-29 00:12
I have to admit that I didn't 'know about InterruptedIOException. 
But I'm wondering that we already catching IOException and throw JedisConnectionException instead.
So if it works, JedisConnectionException should already be detected.
It needs to be tested and confirmed, yet.

**Comment by HeartSaVioR** [comment] 2015-05-29 00:40
Maybe if it works, we should invalidate Jedis instance as same as JedisConnectionException, and throw InterruptedException instead.

**Comment by HeartSaVioR** [comment] 2015-05-30 14:55
Thinking it once more, and realized it is not easy to apply though if it works because InterruptedException is "checked exception" and we should throw InterruptedException from Connection layer to caller.
So IMO although it works it's better to not applying this since it changes whole method's signature.

**Comment by xetorthio** [comment] 2015-05-30 15:12
Yesterday I was discussing with @marcosnils and we realised that when the thread is interrupted and jedis is blocked on `socket.read`, socket should throw an `InterruptedIOException` which jedis will catch and instead throw a `JedisConnectionException`.
So @Grief could use a try and catch block and in case of a `JedisConnectionException` ask the current thread if it was interrupted to decide what to do, by using [Thread.interruped](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#interrupted()).
If this is correct (I am going to test this scenario and post my results) then it seems like there is no need to make any urgent changes to Jedis, right?

**Comment by Grief** [comment] 2015-05-30 17:49
@xetorthio I'd be glad if `native SocketInputStream.socketRead0` throw any exception. But it doesn't, since it relies on the low level OS-specific mechanisms like `recv()` on *nix. 

Just google `SocketInputStream.socketRead0` and find any link without a word `hang` or `stuck` in it. ;)

The solution, probably, requires complete replacement of the usage of this class by any implementation of `java.nio.channels.InterruptibleChannel` interface, e.g. `java.nio.channels.SocketChannel`

**Comment by HeartSaVioR** [comment] 2015-05-31 01:18
@xetorthio @marcosnils @Grief 
Confirmed that below code doesn't interrupt thread. Tested it with OSX 10.10.3.
```
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.exceptions.JedisConnectionException;

import java.io.InterruptedIOException;

public class Test {
  public static void main(String[] args) {
    final JedisPool jedisPool = new JedisPool(new JedisPoolConfig(), "127.0.0.1", 6379,
        2000);
    Thread t = new Thread("Working thread") {
      @Override
      public void run() {
        Jedis jedis = null;
        while (true) {
          try {
            jedis = jedisPool.getResource();

            jedis.brpoplpush("SOURCE", "DESTINATION", 0);
          } catch (JedisConnectionException e) {
            System.out.println("JedisConnectionException occurred : " + e);
            if (e.getCause() instanceof InterruptedIOException) {
              System.out.println("InterruptedIOException occurred : " + e);
              break;
            }
          } finally {
            if (jedis != null) {
              jedis.close();
            }
          }
        }
      }
    };
    t.start();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    while (true) {
      System.out.println("Trying to interrupt thread which is blocked with IO now");
      t.interrupt();
      try {
        Thread.sleep(500);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
  }
}
```

Let's re-think about this.
Interrupting blocking thread which calls OS low level API seems to be completely "OS dependent" issue, which Jedis should not rely on.
I did some googling and found out only stable way to do it closing the socket from other thread. It should be performed by users.

Btw, NIO seems to guarantee it (though we still need to test it with various OS), by closing socket internally.
http://chimera.labs.oreilly.com/books/1234000001805/ch12.html#learnjava3-CHP-12-SECT-5.1
```
 As discussed in Chapter 9, prior to NIO there was no reliable way to stop or wake up a thread blocked in an I/O operation. With NIO, threads blocked in I/O operations always wake up when interrupted or when the channel is closed by anyone. Additionally, if you interrupt a thread while it is blocked in an NIO operation, its channel is automatically closed. (Closing the channel because the thread is interrupted might seem too strong, but usually it’s the right thing to do.)
```

I already wrote about replacement from IO to NIO (#647) so I'm not having strong opinion about this.
(Though it need to upmerge.)
But I'm wondering "supporting interruption of blocking IO thread" could become strong reason to change our base IO to NIO.

**Comment by Grief** [comment] 2015-05-31 08:59
@HeartSaVioR Please re-open this issue, let us start with that.
Changes, contained in the pull request you mentioned look very nice to me. But this is the question to the authors.

**Comment by HeartSaVioR** [comment] 2015-05-31 09:03
@Grief 
OK. Since we don't decide it yet, I'll reopen this issue. Please note that I can close this issue again based on decision.

**Comment by marcosnils** [comment] 2015-05-31 15:26
@Grief take into account that the inclusion of NIO is still not scheduled even though there's already a PR for it. Just wanted to let you know that in case you're looking forward for that fix to be released soon.

**Comment by xetorthio** [comment] 2015-05-31 15:34
Do if java in the docs state something but in reality different OSs behaves
differently. How can we make sure that the same is not true for
SocketChannel?

**Comment by marcosnils** [comment] 2015-06-01 00:42
@Grief I believe that for the moment your only option is to interrupt the thread and close the socket which  holds the BRPOPLPUSH manually. That way to can do something like:


```java
public class MainTest {
    public static void main(String[] args) throws IOException {
        final JedisPool jedisPool = new JedisPool(new JedisPoolConfig(), "127.0.0.1", 6379, 2000);
        final Jedis jedis = jedisPool.getResource();
        Thread t = new Thread("Working thread") {
            @Override
            public void run() {
                while (true) {
                    try {

                        jedis.brpoplpush("SOURCE", "DESTINATION", 0);
                    } catch (JedisConnectionException e) {
                        if (Thread.interrupted()) {
                            System.out.println("Thread was interrupted");
                        } else {
                            System.out.println("There was a connection problem to redis, need to do something else.");
                        }
                    } finally {
                        if (jedis != null) {
                            jedis.close();
                        }
                    }
                }
            }
        };
        t.start();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        t.interrupt();
        jedis.getClient().getSocket().close();
    }
}
```

I believe it's the "best" approach until we move to NIO as we can't do anything else if the thread is blocked reading through the socket

**Comment by Stexxen** [comment] 2015-09-01 11:45
my 2c and my use case for the need to Interrupt.
 
I'm using ListOperations.rightPop with timeout in a web application.
If I shutdown the webapp while the operation is in progress, all threads terminate except the one doing the rightPop.
After the timeout has expired, the following exception occurs, and the application finally shuts down.

```
org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [redis.clients.util.IOUtils]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [redis.clients.util.IOUtils]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1335)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1321)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1203)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1164)
	at redis.clients.jedis.Connection.disconnect(Connection.java:183)
	at redis.clients.jedis.BinaryClient.disconnect(BinaryClient.java:942)
	at redis.clients.jedis.BinaryJedis.disconnect(BinaryJedis.java:1645)
	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:71)
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:890)
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:606)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:64)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:124)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:12)
```

**Comment by marcosnils** [comment] 2015-09-01 16:39
@Stexxen per my previous comment, you should be able to interrupt the thread and close the socket which is blocking in the rightPop which would trigger and exception. You can put this logic in your application server shutdown hooks.

**Comment by Stexxen** [comment] 2015-09-01 17:09
@marcosnils Thanks. Sorry I hadn't seen the 
```
jedis.getClient().getSocket().close()
```
at the bottom to realise what it did.

**Closed** 2015-09-01 17:15 UTC

**Comment by Stexxen** [comment] 2015-09-10 13:06
Actually, can you elaborate further? 
I understand your example. But say you have a pool with multiple connections, how can you get all the clients to then call getSocket().close() on then? it doesn't seem to be possible.

**Comment by Stexxen** [comment] 2015-09-10 13:28
Further Info.
JedisPool inherits from GenericObjectPool. On calling clear() is only destroys connections that are not in use. So there doesn't appear to be any way of closing the socket on blocking pooled connections.

Should this ticket be reopened?

**Comment by msdalp** [comment] 2018-05-11 11:40
Is it expected behavior to get no exception at all  when we are stopping web app with `tomcat stop`. 
```java
public class MyContextListener implements ServletContextListener {
    private final DataListener RawListener = new DataListener();

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        RawListener.start();
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
        RawListener.interrupt();
    }
}
```
On a jax-rs web app having this context with below Thread is not triggering any exception at all. 
```java
public class DataListener extends Thread {

    private boolean dataProcessOn;

    public DataListener() {
        super("DataListener");
        dataProcessOn = true;
    }

    @Override
    public void run() {
        while (dataProcessOn && !this.interrupted()) {
            try (Jedis redis = RedisPool.getJedis()) {
                final String baseData = redis.brpoplpush(
                        "rawdata:stream",
                        "ws:v1:rawdata:processing",
                        0);

                processData(baseData);
            }
        }
    }
}
```
