### ISSUE TITLE
Issue occurs everyday post running redis connections for a day 

### ISSUE THREAD

**Issue by ananth-3** [xetorthio/jedis#1150] opened 2015-11-13 05:26 UTC
We get the following exception everyday , after running for almost 20 hours . 

>"""13-11-2015 10:46:47:016"" ""SEVERE"" ""895806"" "redisredis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
>        at redis.clients.util.Pool.getResource(Pool.java:42)
 >       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:84)
 >       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>Caused by: java.util.NoSuchElementException: Pool exhausted
        at >org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:455)
        at >org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
        at redis.clients.util.Pool.getResource(Pool.java:40)

The JedisPoolConfig that we follow 

**JedisPoolConfig redisConfigs=new JedisPoolConfig();
redisConfigs.setMaxTotal(RedisConstants.numberOfRedisConnections);//128
redisConfigs.setBlockWhenExhausted(false);
redisConfigs.setMaxWaitMillis(timeoutConnection);//5000**

We are a bit confused on setting the maximum number of Redis connections. We close the redis connections using jedis.close() post usage. 

Jedis jar used jedis-2.5.1.jar
Redis version : 2.4.8
commons-pool jar used : commons-pool2-2.2.jar

Can you let us know what we are doing wrong here?

**Comment by HeartSaVioR** [comment] 2015-11-15 21:15
@ananth-3 
Could you post code snippets which initializes JedisPool and borrow/return Jedis instance?
Thanks!

**Comment by ananth-3** [comment] 2015-11-16 04:47
public Jedis getJedis() {
		Jedis jedis=jedisPool.getResource();
		return jedis;
	}

void connect()
	{
		
		JedisPoolConfig redisConfigs=new JedisPoolConfig();
		redisConfigs.setMaxTotal(RedisConstants.numberOfRedisConnections);
		redisConfigs.setBlockWhenExhausted(false);
		redisConfigs.setMaxWaitMillis(timeoutConnection);
		if(timeoutConnection!=null)
		{
			this.jedisPool= new JedisPool(redisConfigs, redisHost, redisPort, timeoutConnection);
		}
		else
		{
			this.jedisPool= new JedisPool(redisConfigs,redisHost,redisPort);
		}
		
	}
	void returnResource(Jedis jedis)
	{
			jedis.close();
	}

**Comment by panchenko** [comment] 2015-11-16 12:58
Are you sure connection is always returned to pool? You'd better use try-with-resources:
```java
try (Jedis jedis = jedisPool.getResource()) {
  // do something with jedis
}
```

**Comment by ananth-3** [comment] 2015-11-16 13:23
I have changed that already . But the version was shown as deprecated in 2.7.2. From which version , should we use close() then. Am not sure if thats the source of the problem.

**Comment by panchenko** [comment] 2015-11-16 13:37
If pool is exhausted, then it is quite likely instances are not returned back.
Try-with-resources syntax ensures an instance is closed (i.e. returned to the pool) even if an exception happens.

**Comment by ananth-3** [comment] 2015-11-16 13:50
@panchenko  Really dont understand. Do you mean to say that returnResource or close is not worth relying upon?

**Comment by panchenko** [comment] 2015-11-16 15:11
@ananth-3 I mean you should try-with-resources.

**Comment by ananth-3** [comment] 2015-11-18 06:19
Will try that and let you know . 

Even returnResource didnt work as I thought there is some problem with respect to close in jedis-2.5.1.

What will happen if there is an intermittent connection failure with respect to Redis. Will the connections hog?

**Comment by marcosnils** [comment] 2015-11-22 05:08
@ananth-3 have you had any updates?

**Comment by ananth-3** [comment] 2015-11-27 07:40
@marcosnils  Testing in progress. Facing socket timeouts in addition to this as we had set 500 ms for max wait time. Planning to increase the timeout to 1500 ms but have no idea on why this should be so high for a cache. Can you provide some idea on this too?

**Comment by panchenko** [comment] 2015-11-27 08:59
@ananth-3 I afraid the only idea is that timeout depends on your hardware/network/workload. I think the default of 2 seconds is OK.

**Comment by marcosnils** [comment] 2015-12-08 05:59
ping?

**Comment by nitinbhatia-dev** [comment] 2016-04-17 06:42
Hi,

Any updates on this issue.
We are redis version 3.0.1 and jedis client 2.7.2
We are facing the exact issue.  Keep on getting this on a daily basis

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the poolredis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed outCaused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refusedredis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

Thanks,
Nitin

**Comment by jamesinc** [comment] 2016-06-09 23:40
+1 we are experiencing this issue too.

**Comment by sheinbergon** [comment] 2016-07-16 21:27
@jamesinc @ananth-3 @nitinbhatia-dev how was this issue handled ? Do you still encounter this issue. I've used jedis under mass scale  ( thousands of ops/second per  server , several  servers ) on a production environment and have encountered no such issues . I can help with general design debugging to help better understand the scenario which causes this issue.

**Comment by PinZhang** [comment] 2016-07-29 08:22
+1 we are experiencing this issue too.

**Comment by marcosnils** [comment] 2016-07-29 10:26
I'm closing this as it's super outdated and it doesn't provide any help at all.

**Closed by marcosnils** 2016-07-29 10:26 UTC

**Comment by imran1609** [comment] 2016-08-18 07:03
@marcosnils 
hi marcosnils ,
I am using jedis 2.9.0 version and when i am using these two method i am getting error(unsafe and unchecked operation).
jedis.close();
JedisPoolConfig jedisPoolConfig = 	new JedisPoolConfig();
			jedisPoolConfig.setMaxTotal(100);

**Comment by sheinbergon** [comment] 2016-08-22 12:11
@imran1609 please provide a full code snippet/excerpt and the full exception stacktrace you're encountering

**Comment by rschiavi** [comment] 2017-05-12 04:02
i'm seeing this as well. here's the sample code. The class constructor has this, and a pool instance variable:

```
JedisPoolConfig config = new JedisPoolConfig();
config.setTestWhileIdle(true);
config.setTestOnBorrow(false);
config.setMaxTotal(2);
config.setBlockWhenExhausted(false);
 if (password != null){
       this.pool = new JedisPool(config, host, port, 60000, password);
 } else {
       this.pool = new JedisPool(config, host, port, 60000);
  }
```

I then just setup a simple timer and call this "flush" function repeatedly, after the 2nd time, I get the exception below. I've tried both the try (Jedis) and calling close myself (and tracking open/close) and not leaking connections.

```
    public synchronized void flush(String channel){
        try (Jedis jedis = pool.getResource()) {
            String job_message = jedis.lpop(this.queue);
            log.info("Job message " + job_message);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
```

â20:55:37,060 ERROR proteus_worker:133 - s.messaging.Subscriber.flush(Subscriber.java:133) - redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
 âredis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:42)
	at s.messaging.Subscriber.flush(Subscriber.java:108)
	at s.messaging.Subscriber.onMessage(Subscriber.java:158)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)
	at s.messaging.Subscriber.run(Subscriber.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Pool exhausted
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:455)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.util.Pool.getResource(Pool.java:40)
	... 11 more
