### ISSUE TITLE
Accept empty password as no password

### ISSUE THREAD

**Issue by scadgek** [xetorthio/jedis#1397] opened 2016-09-26 20:26 UTC
### Expected behavior

`new Jedis( host, port, timeout, null ); // works OK`
`new Jedis( host, port, timeout, "" ); // should work OK, since empty String is no password`

### Actual behavior

`new Jedis( host, port, timeout, null ); // works OK`
`new Jedis( host, port, timeout, "" ); // throws JedisConnectionException`

I also prepared some tests, which demonstrate this problem: https://github.com/scadgek/TestTheThings/blob/master/src/test/java/JedisPoolTests.java

Actually, the reason it's needed is that Redis credentials might be specified in a `.properties` file, and configuration for Redis without authentication would require removing the whole property instead of its value only.

For example, this is the valid config:
```
redis.host = localhost
redis.port = 6379
```

And this is not:
```
redis.host = localhost
redis.port = 6379
redis.password =
```

**Comment by marcosnils** [comment] 2016-09-26 23:11
@scadgek thx for reporting the bug. Would like to craft a PR to fix it?

**Comment by jiafu1115** [comment] 2016-09-27 08:42
can redis allow password is empty but need username?

**Comment by scadgek** [comment] 2016-09-27 09:43
@marcosnils not sure it's a bug, but definitely would be a nice feature I suppose :)
Yes I'll try to make a PR soon.

@jiafu1115 as far as I'm concerned, Redis' authentication scheme does not involve a concept of user

**Comment by marcosnils** [comment] 2016-09-27 14:23
@scadgek you're right, this is not a bug. Redis returns an error when trying to set an empty password so I believe Jedis should follow the same approach as it's a Redis driver.

```
marcos@XPS:~$ telnet localhost 6379
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
*2
$4
auth
$0

-ERR Client sent AUTH, but no password is set
```

Hmm I don't like the idea of manually handling `""` cases as that might produce unexpected behavior. 

@HeartSaVioR ?

**Comment by HeartSaVioR** [comment] 2016-09-27 15:10
@marcosnils Agreed. I guess I saw relevant requests / asks several times. Once Redis treats empty string to valid input for AUTH, it would be safe to just follow it.

**Comment by marcosnils** [comment] 2016-09-27 15:18
@HeartSaVioR perfect. Let's close this issue for now

**Closed** 2016-09-27 15:18 UTC
